name: auth_artboards
description: The artboards that make up the authentication flow.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  navigation_components:
    path: ../navigation_components
  button_components:
    path: ../button_components
  services:
    path: ../services
  full_screen_artboard_templates:
    path: ../full_screen_artboard_templates
  floating_artboard_templates:
    path: ../floating_artboard_templates
  table_components:
    path: ../table_components
  sorting:
    path: ../sorting
  table_artboard_mixin:
    path: ../table_artboard_mixin

dev_dependencies:
  flutter_test:
    sdk: flutter
