name: auth_artboards
description: The artboards that make up the authentication flow.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  navigation_components:
    path: ../navigation_components
  button_components:
    path: ../button_components
  services:
    path: ../services
  artboard_templates:
    path: ../artboard_templates
  artboard_navigators:
    path: ../artboard_navigators
  table_components:
    path: ../table_components
  sorting:
    path: ../sorting
  roof_table:
    path: ../roof_table

dev_dependencies:
  flutter_test:
    sdk: flutter
