name: roller_column_builder
description: Picker with vertical endless scrolling list view.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  labeled_value:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: labeled_value
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: theme
  curve:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/curve
  duration:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/duration
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/distance
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/haptics
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/typography

dev_dependencies:
  flutter_test:
    sdk: flutter