name: roller_column_builder
description: Picker with vertical endless scrolling list view.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  titled_value:
    path: ../../titled_value
  theme:
    path: ../../theme
  curve:
    path: ../../spec/curve
  duration:
    path: ../../spec/duration
  distance:
    path: ../../spec/distance
  haptics:
    path: ../../lib/haptics
  typography:
    path: ../../spec/typography

dev_dependencies:
  flutter_test:
    sdk: flutter