name: input_dock_builder
description: Input dock functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  decorated_text:
    path: ../../lib/decorated_text
  haptics:
    path: ../../lib/haptics
  standard_icon_library:
    path: ../../icons/standard
  image_picker_builder:
    path: ../image_picker
  padding:
    path: ../../spec/padding
  corner_radius:
    path: ../../spec/corner_radius
  distance:
    path: ../../spec/distance
  duration:
    path: ../../spec/duration
  curve:
    path: ../../spec/curve
  theme:
    path: ../../theme
  typography:
    path: ../../spec/typography
  button_builder:
    path: ../../builders/button

dev_dependencies:
  flutter_test:
    sdk: flutter
