name: tag_builder
description: Tag widget builder.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: spec/distance
  corner_radius:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: spec/corner_radius
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: theme
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: spec/typography
  tag_kind_option:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: options/tag_kind

dev_dependencies:
  flutter_test:
    sdk: flutter
