name: empty_vertical_floating_artboard_template
description: An empty vertical floating frame for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    path: ../../../artboard
  vertical_floating_artboard_button_option:
    path: ../../../vertical_floating_artboard_button_option
  vertical_floating_artboard_template_utils:
    path: ../../../artboard_template_utils/vertical_floating

dev_dependencies:
  flutter_test:
    sdk: flutter
