name: nav_button_builder
description: Nav bar button functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/haptics
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: spec/distance
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: theme
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: spec/typography
  navigation_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/navigation
  svg:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: svg
  typedefs:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/typedefs

dev_dependencies:
  flutter_test:
    sdk: flutter
