name: file_upload_artboards
description: The artboards used to upload files via camera or gallery.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vertical_full_screen_artboard_templates:
    path: ../../artboard_templates/vertical_full_screen
  vertical_floating_artboard_templates:
    path: ../../artboard_templates/vertical_floating
  navigator:
    path: ../../lib/navigator
  icon_library:
    path: ../../icon_library
  image_picker: ^0.5.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter
