name: model
description: Tools to reference and persist model objects.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  strings: ^0.1.0
  disk:
    path: ../disk
  types:
    path: ../types
  date:
    path: ../date

dev_dependencies:
  flutter_test:
    sdk: flutter
