name: table_builder
description: Table functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/table
  decorated_text:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/decorated_text
  sorting:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/sorting
  mask:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/mask
  standard_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/standard
  key_value_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/key_value
  key_value_row_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/key_value_row
  spaced_grid_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/spaced_grid
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/haptics
  date:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/date
  tag_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/tag
  invoice_options:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: types/invoice
  request_status:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: types/request
  lease_status:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: types/lease
  tag_kind_option:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: options/tag_kind
  semantic_theme:
    path: ../../semantic_theme

dependency_overrides:
  key_value_builder:
    path: ../key_value
  key_value_row_builder:
    path: ../key_value_row
  spaced_grid_builder:
    path: ../spaced_grid
  tag_builder:
    path: ../tag

dev_dependencies:
  flutter_test:
    sdk: flutter
