name: table_builder
description: Table functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table:
    path: ../../lib/table
  decorated_text:
    path: ../../lib/decorated_text
  sorting:
    path: ../../lib/sorting
  mask:
    path: ../../lib/mask
  icon_library:
    path: ../../icon_library
  distance:
    path: ../../spec/distance
  corner_radius:
    path: ../../spec/corner_radius
  theme:
    path: ../../theme
  typography:
    path: ../../spec/typography
  key_value_builder:
    path: ../key_value
  key_value_row_builder:
    path: ../key_value_row
  spaced_grid_builder:
    path: ../spaced_grid
  haptics:
    path: ../../lib/haptics
  date:
    path: ../../lib/date
  tag_builder:
    path: ../tag

dev_dependencies:
  flutter_test:
    sdk: flutter
