name: event_meta_value_type

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  string_from_enum_string:
    path: ../../lib/string_from_enum_string
  date:
    path: ../../lib/date

dev_dependencies:
  flutter_test:
    sdk: flutter
