name: Sandbox
description: Testing.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth_artboards:
    path: ../auth_artboards
  input_dock_artboard_mixin:
    path: ../input_dock_artboard_mixin
  input_dock_components:
    path: ../input_dock_components
  icon_library:
    path: ../icon_library
  theme:
    path: ../theme
  thread_artboards:
    path: ../thread_artboards

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: azo
      fonts:
        - asset: packages/typography/fonts/azo/AzoSans-Thin.otf
          weight: 100
        - asset: packages/typography/fonts/azo/AzoSans-Light.otf
          weight: 200
        - asset: packages/typography/fonts/azo/AzoSans-Regular.otf
          weight: 300
        - asset: packages/typography/fonts/azo/AzoSans-Medium.otf
          weight: 400
        - asset: packages/typography/fonts/azo/AzoSans-Bold.otf
          weight: 500
