name: full_screen_artboard_templates
description: Templates the define the visual organization for full screen artboards.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_artboard_mixin:
    path: ../table_artboard_mixin
  input_dock_artboard_mixin:
    path: ../input_dock_artboard_mixin
  floating_artboard_templates:
    path: ../floating_artboard_templates

dev_dependencies:
  flutter_test:
    sdk: flutter
