name: date_picker_builder
description: Date picker functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^1.3.16
  haptics:
    path: ../../lib/haptics
  date:
    path: ../../lib/date
  theme:
    path: ../../theme
  typography:
    path: ../../spec/typography
  artboard:
    path: ../../lib/artboard
  icon_library:
    path: ../../icon_library

dev_dependencies:
  flutter_test:
    sdk: flutter
