name: padded_list_builder
description: Listview with horizontal and bottom padding.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  theme:
    path: ../../theme
  distance:
    path: ../../spec/distance

dev_dependencies:
  flutter_test:
    sdk: flutter
