name: option_picker_builder
description: Option selector functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/haptics
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: theme
  small_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/small
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: spec/typography
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/artboard
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/navigator
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: spec/distance
  labeled_value:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: labeled_value

dev_dependencies:
  flutter_test:
    sdk: flutter
