name: tag_editor_builder
description: Tag editor functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/haptics
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: theme
  small_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: icons/small
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/typography
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/artboard
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/navigator
  curve:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/curve
  duration:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/duration
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/distance
  labeled_icon:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: labeled_icon
  tag_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: builders/tag

dev_dependencies:
  flutter_test:
    sdk: flutter
