name: keyboard_accessory_bar_builder
description: Keyboard accessory bar functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  multi_image_picker: ^3.0.23
  flutter:
    sdk: flutter
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: spec/distance
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: theme
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: spec/typography
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/haptics

dev_dependencies:
  flutter_test:
    sdk: flutter
