name: interval_frequency_picker_data

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  frequency_type:
    path: ../types/frequency

dev_dependencies:
  flutter_test:
    sdk: flutter
