name: artboard_templates
description: Templates the define the visual organization.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  navigation_components:
    path: ../navigation_components
  button_components:
    path: ../button_components
  roof_form:
    path: ../roof_form
  roof_table:
    path: ../roof_table
  services:
    path: ../services

dev_dependencies:
  flutter_test:
    sdk: flutter
