name: input_dock_components
description: Widgets that make up the input dock.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spec:
    path: ../spec
  theme:
    path: ../theme
  typography:
    path: ../typography
  haptics:
    path: ../haptics
  icon_library:
    path: ../icon_library

dev_dependencies:
  flutter_test:
    sdk: flutter
