name: app
description: Delightful renting for roommates and landlords.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  theme:
    path: ../../theme
  public_activity_artboard:
    path: ../../artboards/public_activity
  vertical_full_screen_artboard_scaffold:
    path: ../../artboard_scaffolds/vertical_full_screen
  artboard:
    path: ../../lib/artboard
  device_screen:
    path: ../../lib/device_screen
  mqtt_client: ^5.5.3
  pointycastle: ^1.0.1
  asn1lib: ^0.5.8
  googleapis_auth: ^0.2.7
  googleapis: ^0.53.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - priv.txt
    - roots.pem
    - rsa_private.pem
    - ec_private.pem

  fonts:
    - family: azo
      fonts:
        - asset: packages/typography/fonts/azo/AzoSans-Thin.otf
          weight: 100
        - asset: packages/typography/fonts/azo/AzoSans-Light.otf
          weight: 200
        - asset: packages/typography/fonts/azo/AzoSans-Regular.otf
          weight: 300
        - asset: packages/typography/fonts/azo/AzoSans-Medium.otf
          weight: 400
        - asset: packages/typography/fonts/azo/AzoSans-Bold.otf
          weight: 500
