name: form_artboard_mixin
description: Form functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  form:
    path: ../form
  form_components:
    path: ../form_components

dev_dependencies:
  flutter_test:
    sdk: flutter
