name: commands
description: Framework for issuing commands.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+3
  device_info: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
