name: collapsible_container_builder
description: Container that can be collapsed by a parent to 0 height.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  duration:
    path: ../../spec/duration
  curve:
    path: ../../spec/curve
  visibility_manager_builder:
    path: ../../builders/visibility_manager
  visibility_manager:
    path: ../../visibility_manager

dev_dependencies:
  flutter_test:
    sdk: flutter