name: empty_horizontal_floating_artboard_template
description: An empty horizontal floating frame for building a widget hierarchy in.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    path: ../../../artboard
  horizontal_floating_artboard_template_utils:
    path: ../../../artboard_template_utils/horizontal_floating

dev_dependencies:
  flutter_test:
    sdk: flutter
