name: tabbed_container_builder
description: Container with tab bar and tab views.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  icon_library:
    path: ../../icon_library
  typography:
    path: ../../spec/typography
  theme:
    path: ../../theme
  haptics:
    path: ../../lib/haptics
  distance:
    path: ../../spec/distance
  visibility_manager_builder:
    path: ../visibility_manager
  collapsible_container_builder:
    path: ../collapsible_container
  input_dock_builder:
    path: ../input_dock

dev_dependencies:
  flutter_test:
    sdk: flutter
