name: app
description: Delightful renting for roommates and landlords.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table:
    path: ../table
  roof_form:
    path: ../roof_form
  services:
    path: ../services
  icon_library:
    path: ../icon_library
  decorated_text:
    path: ../decorated_text
  artboard_templates:
    path: ../artboard_templates
  navigation_components:
    path: ../navigation_components
  theme:
    path: ../theme
  table_components:
    path: ../table_components
  routing:
    path: ../routing

dev_dependencies:
  flutter_test:
    sdk: flutter
