name: model_object

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain_type:
    path: ../../../types/domain
  mappable:
    path: ../../mixins/mappable
  key:
    path: ../../key
  date:
    path: ../../../lib/date

dev_dependencies:
  flutter_test:
    sdk: flutter
