name: name_contract_domain

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  context_type:
    path: ../../../types/context
  key:
    path: ../../key
  name_domain:
    path: ../name_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
