name: time_picker_builder
description: Component for selecting a time of day

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    path: ../../lib/artboard
  theme:
    path: ../../theme
  duration:
    path: ../../spec/duration
  curve:
    path: ../../spec/curve
  haptics:
    path: ../../lib/haptics
  labeled_value:
    path: ../../labeled_value
  roller_column_picker_builder:
    path: ../roller_column_picker
  typography:
    path: ../../spec/typography

dev_dependencies:
  flutter_test:
    sdk: flutter
