name: input_dock_artboard_mixin
description: Input dock functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  input_dock_components:
    path: ../input_dock_components
  decorated_text:
    path: ../decorated_text
  icon_library:
    path: ../icon_library

dev_dependencies:
  flutter_test:
    sdk: flutter
