name: stack_vertical_floating_artboard_template
description: An vertical floating frame with body and a button stack for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/artboard
  vertical_floating_artboard_scaffold:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: artboard_scaffolds/vertical_floating
  button_stack_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: builders/button_stack

dev_dependencies:
  flutter_test:
    sdk: flutter
