name: app_data
description: An interface to interact with app data.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.4.0+1
  network:
    path: ../lib/network
  synchronizer:
    path: ../synchronizer
  session:
    path: ../session
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter
