name: public_activity_artboard
description: Allows the user to see a public activity feed.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  full_logo_table_vertical_full_screen_artboard_template:
    path: ../../artboard_templates/vertical_full_screen/full_logo_table
  sign_up_artboard:
    path: ../sign_up
  app_data:
    path: ../../app_data
  nav_button_builder:
    path: ../../builders/nav_button
  icon_library:
    path: ../../icon_library
  public:
    path: ../../model/objects/public
  navigator:
    path: ../../lib/navigator

dev_dependencies:
  flutter_test:
    sdk: flutter
