name: public_activity_artboard
description: Allows the user to see a public activity feed.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  empty_table_vertical_full_screen_artboard_template:
      path: ../../artboard_templates/vertical_full_screen/empty_table
  sign_up_artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: artboards/sign_up
  app_data:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: app_data
  nav_button_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/nav_button
  navigation_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/navigation
  standard_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/standard
  x_small_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/x_small
  public:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: model/objects/public
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/navigator
  views:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: views
  button_stack_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/button_stack
  commands:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: commands
  button_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/button

dependency_overrides:
  nav_button_builder:
    path: ../../builders/nav_button
  button_stack_builder:
    path: ../../builders/button_stack
  button_builder:
    path: ../../builders/button

dev_dependencies:
  flutter_test:
    sdk: flutter
