name: icon_library
description: Roof's icon library.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.10.2

flutter:
  assets:
    - navigation/
    - basic/
