name: date_picker_artboard
description: Allows the user to chose a date.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vertical_floating_artboard_templates:
    path: ../../artboard_templates/vertical_floating
  form_builder:
    path: ../../builders/form
  date_picker_builder:
    path: ../../builders/date_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
