name: commands
description: Library for issuing commands via blossm

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+3
  device_info: ^0.4.0+1
  blossm_command:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-sm-app
      path: blossm_command
  secure_storage:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-sm-app
      path: lib/secure_storage

dependency_overrides:
  blossm_command:
    path: ../../blossm_command

dev_dependencies:
  flutter_test:
    sdk: flutter
