name: button_stack_builder
description: Functionality for displaying a collection of buttons in an artboard.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  distance:
    path: ../../spec/distance
  theme:
    path: ../../theme
  typography:
    path: ../../spec/typography

dev_dependencies:
  flutter_test:
    sdk: flutter
