name: auth_artboards
description: The artboards that make up the authentication flow.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  full_screen_artboard_templates:
    path: ../../artboard_templates/full_screen
  floating_artboard_templates:
    path: ../../artboard_templates/floating
  app_data:
    path: ../../app_data
  challenge_artboards:
    path: ../challenge
  nav_button_builder:
    path: ../../builders/nav_button
  icon_library:
    path: ../../icon_library
  navigation:
    path: ../../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
