name: synchronizer
description: A tool to parse data recieved by the server.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  network:
    path: ../lib/network

dev_dependencies:
  flutter_test:
    sdk: flutter
