name: caret_wrap_builder
description: Wrap that inserts right-facing carets between children.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  x_small_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: icons/x_small
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/typography
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: theme
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/haptics
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/distance

dev_dependencies:
  flutter_test:
    sdk: flutter
