name: task

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fee_payer_type:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: types/fee_payer
  assignment_type:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: types/assignment
  key:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/key
  name_defining_object:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/mixins/name_defining_object
  user_reference:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/properties/user_reference
  completion_count:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/properties/completion_count
  commentable_object:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/abstractcommentable_object
  task_reference:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/properties/task_reference
  date:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/date
  schedule:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/properties/schedule
  context:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/abstract/context
  name_user:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/properties/name_user
  date_parts:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/properties/date_parts
  name_formatter:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/name_formatter
  stub:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: model/objects/stub

dev_dependencies:
  flutter_test:
    sdk: flutter
