name: currency
description: A helper to manipulate currency values.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  money: ^0.2.1
  intl: ^0.15.7
  locales: ^0.1.0
