name: image_picker_builder
description: Component for returning images from the device camera or gallery

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  multi_image_picker: ^3.0.23
  flutter:
    sdk: flutter
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: theme

dev_dependencies:
  flutter_test:
    sdk: flutter
