name: synchronize
description: Tools to parse data recieved by the server.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  network:
    path: ../network

dev_dependencies:
  flutter_test:
    sdk: flutter
