name: lease_full_screen_artboard_template
description: A navigable object frame for displaying a lease with a titled nav bar, a breadcrumb stack, an info row table, and a tabbed container with Tenants, Invoices, Messages and Maintenance tabs.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    path: ../../../lib/artboard
  vertical_full_screen_artboard_scaffold:
    path: ../../../artboard_scaffolds/vertical_full_screen
  tabbed_collapsible_fullscreen_artboard_template:
    path: ../tabbed_collapsible
  nav_bar_builder:
    path: ../../../builders/nav_bar
  input_dock_builder:
    path: ../../../builders/input_dock
  table_builder:
    path: ../../../builders/table
  breadcrumb_stack_builder:
    path: ../../../builders/breadcrumb_stack
  tabbed_container_builder:
    path: ../../../builders/tabbed_container
  cells_list_view_builder:
    path: ../../../builders/cells_list_view
  key_value_row_builder:
    path: ../../../builders/key_value_row

dev_dependencies:
  flutter_test:
    sdk: flutter
