name: vertical_floating_artboard_templates
description: Vertical floating frames for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  navigation:
    path: ../../navigation
  artboard:
    path: ../../artboard
  form_builder:
    path: ../../builders/form
  form_body_builder:
    path: ../../builders/form_body
  button_stack_builder:
    path: ../../builders/button_stack
  keyboard_accessory_bar_builder:
    path: ../../builders/keyboard_accessory_bar
  keyboard_accessory:
    path: ../../lib/keyboard_accessory
  date_picker_artboard:
    path: ../../artboards/date_picker
  nav_button_builder:
    path: ../../builders/nav_button
  vertical_floating_artboard_button_option:
    path: ../../vertical_floating_artboard_button_option
  date:
    path: ../../lib/date
  theme:
    path: ../../theme
  duration:
    path: ../../duration
  curve:
    path: ../../curve
  distance:
    path: ../../distance

dev_dependencies:
  flutter_test:
    sdk: flutter
