name: form_body_builder
description: Form functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  semantic_theme:
    path: ../../semantic_theme
  keyboard_accessory_bar_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/keyboard_accessory_bar
  date_picker_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/date_picker
  standard_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/standard
  small_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: icons/small
  mask:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/mask
  form:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/form
  keyboard_accessory:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/keyboard_accessory
  date:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/date
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/haptics
  ordinal_suffix_string_from_int:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/ordinal_suffix_string_from_int
  form_validation_exception:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/form_validation_exception
  typedefs:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/typedefs
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/artboard
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: lib/navigator
  labeled_value:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: labeled_value
  labeled_icon:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: labeled_icon
  frequency:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: frequency
  time_picker_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/time_picker
  interval_frequency_picker_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/interval_frequency_picker
  roller_column_picker_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/roller_column_picker
  tag_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/tag
  tag_editor_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/tag_editor
  icon_picker_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/icon_picker
  option_picker_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: semantic-theme-compatible-builders
      path: builders/option_picker

dependency_overrides:
  keyboard_accessory_bar_builder:
    path: ../keyboard_accessory_bar
  date_picker_builder:
    path: ../date_picker
  time_picker_builder:
    path: ../time_picker
  interval_frequency_picker_builder:
    path: ../interval_frequency_picker
  roller_column_picker_builder:
    path: ../roller_column_picker
  tag_builder:
    path: ../tag
  tag_editor_builder:
    path: ../tag_editor
  icon_picker_builder:
    path: ../icon_picker
  option_picker_builder:
    path: ../option_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
