name: form_body_builder
description: Form functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_accessory_bar_builder:
    path: ../keyboard_accessory_bar
  date_picker_builder:
    path: ../date_picker
  distance:
    path: ../../spec/distance
  duration:
    path: ../../spec/duration
  padding:
    path: ../../spec/padding
  corner_radius:
    path: ../../spec/corner_radius
  curve:
    path: ../../spec/curve
  typography:
    path: ../../spec/typography
  standard_icon_library:
    path: ../../icons/standard
  small_icon_library:
    path: ../../icons/small
  theme:
    path: ../../theme
  mask:
    path: ../../lib/mask
  form:
    path: ../../lib/form
  keyboard_accessory:
    path: ../../lib/keyboard_accessory
  date:
    path: ../../lib/date
  haptics:
    path: ../../lib/haptics
  form_validation_exception:
    path: ../../lib/form_validation_exception
  typedefs:
    path: ../../lib/typedefs
  artboard:
    path: ../../lib/artboard
  navigator:
    path: ../../lib/navigator
  option_picker_artboard:
    path: ../../artboards/shared/option_picker
  icon_picker_artboard:
    path: ../../artboards/shared/icon_picker
  option_picker_data:
    path: ../../option_picker_data
  icon_picker_data:
    path: ../../icon_picker_data
  time_picker_builder:
    path: ../../builders/time_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
