name: form_body_builder
description: Form functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_accessory_bar_builder:
    path: ../keyboard_accessory_bar
  date_picker_builder:
    path: ../date_picker
  distance:
    path: ../../distance
  duration:
    path: ../../duration
  padding:
    path: ../../padding
  corner_radius:
    path: ../../corner_radius
  curve:
    path: ../../curve
  typography:
    path: ../../typography
  icon_library:
    path: ../../icon_library
  theme:
    path: ../../theme
  mask:
    path: ../../lib/mask
  form:
    path: ../../lib/form
  keyboard_accessory:
    path: ../../lib/keyboard_accessory
  date:
    path: ../../lib/date
  haptics:
    path: ../../lib/haptics
  form_validation_exception:
    path: ../../lib/form_validation_exception
  typedefs:
    path: ../../lib/typedefs

dev_dependencies:
  flutter_test:
    sdk: flutter
