name: icon_picker_builder
description: Icon selector functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/haptics
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: theme
  standard_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: icons/standard
  typography:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/typography
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/artboard
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/navigator
  distance:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/distance
  labeled_icon:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: labeled_icon

dev_dependencies:
  flutter_test:
    sdk: flutter
