name: titled_icon

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  standard_icon_library:
    path: ../icons/standard
  titled_value:
    path: ../titled_value

dev_dependencies:
  flutter_test:
    sdk: flutter
