name: challenge_artboards
description: The artboards that make up the phone number challenge flow.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floating_artboard_templates:
    path: ../floating_artboard_templates
  app_data:
    path: ../app_data

dev_dependencies:
  flutter_test:
    sdk: flutter
