name: vertical_full_screen_artboard_scaffold
description: Tools to for scaffolding and navigating to a vertical full screen artboard.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vertical_floating_artboard_scaffold:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: artboard_scaffold/vertical_floating
  horizontal_floating_artboard_scaffold:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: artboard_scaffold/horizontal_floating
  keyboard_accessory:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/keyboard_accessory
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/artboard
  duration:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/duration
  curve:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: spec/curve
  theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: theme
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: packages
      path: lib/navigator

dev_dependencies:
  flutter_test:
    sdk: flutter
