name: vertical_full_screen_artboard_scaffold
description: Tools to for scaffolding and navigating to a vertical full screen artboard.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vertical_floating_artboard_scaffold:
    path: ../vertical_floating
  horizontal_floating_artboard_scaffold:
    path: ../horizontal_floating
  keyboard_accessory:
    path: ../../lib/keyboard_accessory
  artboard:
    path: ../../lib/artboard
  duration:
    path: ../../duration
  curve:
    path: ../../curve
  theme:
    path: ../../theme
  navigator:
    path: ../../lib/navigator

dev_dependencies:
  flutter_test:
    sdk: flutter
