name: form_builder
description: A form with information and buttons.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  button_builder:
    path: ../button
  form_body_builder:
    path: ../form_body
  distance:
    path: ../../distance
  button_status_option:
    path: ../../button_status_option

dev_dependencies:
  flutter_test:
    sdk: flutter
