name: artboard_navigators
description: The navigators that control flow between artboards.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard_templates:
    path: ../artboard_templates
  routing:
    path: ../routing
  theme:
    path: ../theme
  navigation_components:
    path: ../navigation_components
  icon_library:
    path: ../icon_library

dev_dependencies:
  flutter_test:
    sdk: flutter
