name: empty_vertical_full_screen_artboard_template
description: An empty vertical full screen frame for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    path: ../../../artboard
  vertical_full_screen_artboard_template_utils:
    path: ../../../artboard_template_utils/vertical_full_screen

dev_dependencies:
  flutter_test:
    sdk: flutter
