name: table
description: Roof's table tools.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream:
    path: ../stream
  icon_library:
    path: ../icon_library

dev_dependencies:
  flutter_test:
    sdk: flutter
