name: button_dock_builder
description: Button dock that arranges two buttons horizontally at the bottom of the screen.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  theme:
    path: ../../theme
  typography:
    path: ../../typography
  spec:
    path: ../../spec

dev_dependencies:
  flutter_test:
    sdk: flutter
