name: date_picker_artboard_mixin
description: Date picker functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  calendar_date_picker:
    path: ../calendar_date_picker
  haptics:
    path: ../haptics
  date:
    path: ../date

dev_dependencies:
  flutter_test:
    sdk: flutter
